### ISSUE TITLE
Unable to access Save button graphically when working with a large team on a small screen.

### ISSUE THREAD

**Issue by cfrayda** [jahed/agility#9]
Using Chrome (https://agility.jahed.dev/) on a Chromebook in a training situation, we had a large team ~10 that would have been nice to include in rotation. 
We did not find a scroll bar while trying to navigate through the list.
We resorted to tabbing to various name entries, but never mastered tabbing to the Save button. - We gave up and started with a group of 5.
I would be nice to involve the whole group to keep them more engaged and that navigation be obvious for people new to the interface.

**Comment by jahed** [comment]
Should be fixed now. I've enabled scrolling when the modal doesn't fit. Also fixed the tabbing order for the save/shuffle buttons.

**Comment by jahed** [comment]
I said "now", but I meant, whenever GitHub Pages refreshes its caches. So probably in the next hour.

**Comment by cfrayda** [comment]
It's fixed on the web. Thanks!
